hostname taisho

interface 4-23-4
  ip address 10.4.123.7/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-6
  ip address 10.4.123.8/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.5/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.5
