hostname taisho

interface to-ara
  ip address 10.4.123.7/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-hete
  ip address 10.4.123.8/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.5/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.5
