hostname mukomachi

interface 4-2-16
  ip address 10.4.102.5/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-4
  ip address 10.4.102.6/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.3/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.3
