hostname teradacho

interface 4-23-18
  ip address 10.4.123.35/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-1
  ip address 10.4.123.36/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.19/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.19
