hostname shimamoto

interface 4-2-5
  ip address 10.4.102.11/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-6
  ip address 10.4.102.12/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.15/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.15
