hostname kyujoji

interface 4-7-14
  ip address 10.4.107.27/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-7-16
  ip address 10.4.107.28/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.15/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.15
