hostname kishibe

interface 4-2-9
  ip address 10.4.102.23/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-11
  ip address 10.4.102.24/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.10/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.10
