hostname osaka

interface 4-2-13
  ip address 10.4.102.31/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-9
  ip address 10.4.123.17/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-11
  ip address 10.4.123.18/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.14/32
  ip address 10.4.23.10/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.10
