hostname kyobashi

interface to-sara
  ip address 10.4.123.23/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-oshi
  ip address 10.4.123.24/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.13/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.13
