hostname yao

interface to-shiki
  ip address 10.4.107.25/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-kiho
  ip address 10.4.107.26/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.14/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.14
