hostname settsu-tonda

interface 4-2-6
  ip address 10.4.102.15/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-17
  ip address 10.4.102.16/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.7/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.7
