hostname sakuranomiya

interface to-tema
  ip address 10.4.123.21/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-kiha
  ip address 10.4.123.22/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.12/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.12
