hostname sakuranomiya

interface 4-23-11
  ip address 10.4.123.21/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-13
  ip address 10.4.123.22/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.12/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.12
