hostname tamatsukuri

interface 4-23-15
  ip address 10.4.123.29/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-17
  ip address 10.4.123.30/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.16/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.16
