hostname bentencho

interface to-tase
  ip address 10.4.123.9/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-niku
  ip address 10.4.123.10/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.6/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.6
