hostname higashi-yodogawa

interface 4-2-11
  ip address 10.4.102.27/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-13
  ip address 10.4.102.28/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.12/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.12
