hostname nara

interface 4-7-3
  ip address 10.4.107.5/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-7-5
  ip address 10.4.107.6/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.4/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.4
