hostname tsuruhashi

interface 4-23-16
  ip address 10.4.123.31/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-18
  ip address 10.4.123.32/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.17/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.17
