hostname imamiya

interface 4-7-20
  ip address 10.4.107.39/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-7-22
  ip address 10.4.107.40/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-2
  ip address 10.4.123.3/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-23-4
  ip address 10.4.123.4/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.21/32
  ip address 10.4.23.3/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.3
