hostname imamiya

interface to-shiya-yama
  ip address 10.4.107.39/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-naha
  ip address 10.4.107.40/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-shiya
  ip address 10.4.123.3/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-ara
  ip address 10.4.123.4/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.21/32
  ip address 10.4.23.3/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.3
