hostname nishikujo

interface to-hete
  ip address 10.4.123.11/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-nota
  ip address 10.4.123.12/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.7/32
  ip address 10.4.24.1/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.24.1
