hostname oji

interface 4-7-7
  ip address 10.4.107.13/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-7-9
  ip address 10.4.107.14/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.8/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.8
