hostname imamiya

interface to-shiya
  ip address 10.4.123.3/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-ara
  ip address 10.4.123.4/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.3/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.3
