hostname morinomiya

interface to-oshi
  ip address 10.4.123.27/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-tsuri
  ip address 10.4.123.28/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.15/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.15
