hostname takaida

interface to-kachi
  ip address 10.4.107.19/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-kashi
  ip address 10.4.107.20/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.11/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.11
