hostname takatsuki

interface 4-2-15
  ip address 10.4.102.13/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-7
  ip address 10.4.102.14/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.6/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.6
