hostname nagaokakyo

interface 4-2-3
  ip address 10.4.102.7/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface 4-2-5
  ip address 10.4.102.8/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.2.4/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.2.4
