hostname kami

interface to-kiho
  ip address 10.4.107.29/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-hira
  ip address 10.4.107.30/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.16/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.16
