hostname tobushijomae

interface to-hira
  ip address 10.4.107.33/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-ten
  ip address 10.4.107.34/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.18/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.18
