hostname momodani

interface to-tsuha
  ip address 10.4.123.33/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-teta
  ip address 10.4.123.34/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.18/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.18
