hostname yamato-koizumi

interface to-kori
  ip address 10.4.107.9/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-hori
  ip address 10.4.107.10/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.7.6/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.7.6
