hostname fukushima

interface to-nota
  ip address 10.4.123.15/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface to-osa
  ip address 10.4.123.16/31
  ip ospf 1 area 0
  ip ospf network point-to-point

interface lo
  ip address 10.4.23.9/32
  ip ospf 1 area 0

router ospf 1
  ospf router-id 10.4.23.9
